# Generated by Django 4.0.3 on 2024-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=15, unique=True)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
